package datkt.fs

val F_OK = datkt.fs.constants._F_OK()
val R_OK = datkt.fs.constants._R_OK()
val W_OK = datkt.fs.constants._W_OK()
val X_OK = datkt.fs.constants._X_OK()

val O_RDONLY = datkt.fs.constants._O_RDONLY()
val O_WRONLY = datkt.fs.constants._O_WRONLY()
val O_RDWR = datkt.fs.constants._O_RDWR()
val O_CREAT = datkt.fs.constants._O_CREAT()
val O_EXCL = datkt.fs.constants._O_EXCL()
val O_NOCTTY = datkt.fs.constants._O_NOCTTY()
val O_TRUNC = datkt.fs.constants._O_TRUNC()
val O_APPEND = datkt.fs.constants._O_APPEND()
val O_DIRECTORY = datkt.fs.constants._O_DIRECTORY()
val O_NOATIME = datkt.fs.constants._O_NOATIME()
val O_NOFOLLOW = datkt.fs.constants._O_NOFOLLOW()
val O_SYNC = datkt.fs.constants._O_SYNC()
val O_DSYNC = datkt.fs.constants._O_DSYNC()
val O_SYMLINK = datkt.fs.constants._O_SYMLINK()
val O_DIRECT = datkt.fs.constants._O_DIRECT()
val O_NONBLOCK = datkt.fs.constants._O_NONBLOCK()

val S_IFMT = datkt.fs.constants._S_IFMT()
val S_IFREG = datkt.fs.constants._S_IFREG()
val S_IFDIR = datkt.fs.constants._S_IFDIR()
val S_IFCHR = datkt.fs.constants._S_IFCHR()
val S_IFBLK = datkt.fs.constants._S_IFBLK()
val S_IFIFO = datkt.fs.constants._S_IFIFO()
val S_IFLNK = datkt.fs.constants._S_IFLNK()
val S_IFSOCK = datkt.fs.constants._S_IFSOCK()
val S_IRWXU = datkt.fs.constants._S_IRWXU()
val S_IRUSR = datkt.fs.constants._S_IRUSR()
val S_IWUSR = datkt.fs.constants._S_IWUSR()
val S_IXUSR = datkt.fs.constants._S_IXUSR()
val S_IRWXG = datkt.fs.constants._S_IRWXG()
val S_IRGRP = datkt.fs.constants._S_IRGRP()
val S_IWGRP = datkt.fs.constants._S_IWGRP()
val S_IXGRP = datkt.fs.constants._S_IXGRP()
val S_IRWXO = datkt.fs.constants._S_IRWXO()
val S_IROTH = datkt.fs.constants._S_IROTH()
val S_IWOTH = datkt.fs.constants._S_IWOTH()
val S_IXOTH = datkt.fs.constants._S_IXOTH()

val UV_FS_SYMLINK_DIR = datkt.fs.constants._UV_FS_SYMLINK_DIR()
val UV_FS_SYMLINK_JUNCTION = datkt.fs.constants._UV_FS_SYMLINK_JUNCTION()
val UV_DIRENT_UNKNOWN = datkt.fs.constants._UV_DIRENT_UNKNOWN()
val UV_DIRENT_FILE = datkt.fs.constants._UV_DIRENT_FILE()
val UV_DIRENT_DIR = datkt.fs.constants._UV_DIRENT_DIR()
val UV_DIRENT_LINK = datkt.fs.constants._UV_DIRENT_LINK()
val UV_DIRENT_FIFO = datkt.fs.constants._UV_DIRENT_FIFO()
val UV_DIRENT_SOCKET = datkt.fs.constants._UV_DIRENT_SOCKET()
val UV_DIRENT_CHAR = datkt.fs.constants._UV_DIRENT_CHAR()
val UV_DIRENT_BLOCK = datkt.fs.constants._UV_DIRENT_BLOCK()
